In [8]:
#Dimensions
import numpy as np

arr = np.array([1,2,3,4,5])
print(arr)
print("*" * 100)

# 0-D Array
arr = np.array(42)
print(arr)
print("*" * 100)

# 1-D Array
arr = np.array([1, 2 , 3, 4, 5])
print(arr)
print("*" * 100)

# 2-D Array
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)
print("*" * 100)

# 3-D Array
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(arr)  
print("*" * 100)

[1 2 3 4 5]
****************************************************************************************************
42
****************************************************************************************************
[1 2 3 4 5]
****************************************************************************************************
[[1 2 3]
 [4 5 6]]
****************************************************************************************************
[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
3
****************************************************************************************************


In [9]:
# Shape method
import numpy as np

# creating list 
list_1 = [1, 2, 3, 4]
list_2 = [5, 6, 7, 8]
list_3 = [9, 10, 11, 12]


sample_array = np.array([list_1,
                         list_2,
                         list_3])

print("Numpy array :")
print(sample_array)

print("Shape of the array :",
      sample_array.shape)




Numpy array :
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Shape of the array : (3, 4)


In [11]:
#Slicing every dimension
import numpy as np

# Dimension: 1D
arr_1d = np.array([1, 2, 3, 4, 5])
print("1D Array:", arr_1d)
print("Slicing 1D Array:", arr_1d[1:4])  

# Dimension: 2D
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("\n2D Array:")
print(arr_2d)
print("Slicing 2D Array (column):", arr_2d[:, 1:])  

# Dimension: 3D
arr_3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print("\n3D Array:")
print(arr_3d)
print("Slicing 3D Array (element):", arr_3d[:, 1, 1:])

# Dimension: 4D
arr_4d = np.array([[[[1, 2], [3, 4]], [[5, 6], [7, 8]]], [[[9, 10], [11, 12]], [[13, 14], [15, 16]]]])
print("\n4D Array:")
print(arr_4d)
print("Slicing 4D Array (first element):", arr_4d[0, 0, 0, :])  


1D Array: [1 2 3 4 5]
Slicing 1D Array: [2 3 4]

2D Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Slicing 2D Array (column): [[2 3]
 [5 6]
 [8 9]]

3D Array:
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
Slicing 3D Array (element): [[ 5  6]
 [11 12]]

4D Array:
[[[[ 1  2]
   [ 3  4]]

  [[ 5  6]
   [ 7  8]]]


 [[[ 9 10]
   [11 12]]

  [[13 14]
   [15 16]]]]
Slicing 4D Array (first element): [1 2]


In [12]:
# Get the datatype of the array
import numpy as np
arr = np.array(["apple", "banana", "cherry"])
print(arr.dtype)

<U6


In [14]:
# Change data type of the array
# Change float to int
import numpy as np 
arr = np.array([1.1, 2.1, 3.1])
newarr = arr.astype('i')
print(newarr)
print(newarr.dtype)
print("*" * 50)

# Change int to float
import numpy as np 
arr = np.array([1, 0, 3])
newarr = arr.astype(bool)
print(newarr)
print(newarr.dtype)
print("*" * 50)

[1 2 3]
int32
**************************************************
[ True False  True]
bool
**************************************************


In [17]:
# Copy and view in arrays
# Copy() - Changes made to the original does not affect the copy
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
copy = arr.copy()
arr[0] = 42
print(arr)
print(copy)
print("*" * 50)

# View() - Changes made to the original will affect the view
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
copy = arr.view()
arr[0] = 31
print(arr)
print(copy)
print("*" * 50)

[42  2  3  4  5]
[1 2 3 4 5]
**************************************************
[31  2  3  4  5]
[31  2  3  4  5]
**************************************************


In [18]:
# Reshape - Changes the number of rows and coloums of the matrix
import numpy as np

# Creating a 1D array with 12 elements
arr = np.arange(12)
print("Original 1D array:")
print(arr)
print("*" * 50)

# Reshaping the 1D array into a 3x4 2D array
arr_2d = arr.reshape(3, 4)
print("\nReshaped 2D array:")
print(arr_2d)
print("*" * 50)

# Reshaping the 1D array into a 3x2x2 3D array
arr_3d = arr.reshape(3, 2, 2)
print("\nReshaped 3D array:")
print(arr_3d)
print("*" * 50)


Original 1D array:
[ 0  1  2  3  4  5  6  7  8  9 10 11]
**************************************************

Reshaped 2D array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
**************************************************

Reshaped 3D array:
[[[ 0  1]
  [ 2  3]]

 [[ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]]]
**************************************************


In [19]:
# Iterating
import numpy as np

# 1D array
arr_1d = np.array([1, 2, 3, 4, 5])
print("1D Array:")
for i in arr_1d:
    print(i, end=' ')
print("\n")

# 2D array
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("2D Array:")
for row in arr_2d:
    for elem in row:
        print(elem, end=' ')
    print()
print()

# 3D array
arr_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]], [[9, 10], [11, 12]]])
print("3D Array:")
for depth in arr_3d:
    print("Depth:")
    for row in depth:
        for elem in row:
            print(elem, end=' ')
        print()
    print()


1D Array:
1 2 3 4 5 

2D Array:
1 2 3 
4 5 6 
7 8 9 

3D Array:
Depth:
1 2 
3 4 

Depth:
5 6 
7 8 

Depth:
9 10 
11 12 



In [25]:
# nditor() to iterate
import numpy as np
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

for value in np.nditer(arr):
    print(value, end=" ")

1 2 3 4 5 6 7 8 

In [1]:
# ndenumerate() - Gets the index position of the element in the array
import numpy as np
arr = np.array(["Cherry", "Pineapple", "Watermelon"])
for idx, x in np.ndenumerate(arr):
    print(idx[0], x) 


0 Cherry
1 Pineapple
2 Watermelon


In [2]:
import numpy as np

arr = np.array([1,2,3,4], ndmin=5)
print(arr)
print("Number of dimensions: ", arr.ndim)

[[[[[1 2 3 4]]]]]
Number of dimensions:  5


In [59]:
import numpy as np

import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

# Printing the 2nd element in the 1st dimension using indexing
print("2nd element on 1st dimension (indexing):", arr[0][1])

# Printing the 2nd element in the 1st dimension using slicing
print("2nd element on 1st dimension (slicing):", arr[0, 1])

# Printing all values in reverse order
print("Slicing (all values in reverse):", arr[::-1, ::-1])

# Using map and lambda to iterate through each element and print
print("Using map and lambda to iterate through each element and print:")
print(list(map(lambda a: a, arr)))

# Using a for loop to iterate through each element and print
print("Using a for loop to iterate through each element and print:")
print(*(element for element in arr))





2nd element on 1st dimension (indexing): 2
2nd element on 1st dimension (slicing): 2
Slicing (all values in reverse): [[10  9  8  7  6]
 [ 5  4  3  2  1]]
Using map and lambda to iterate through each element and print:
[array([1, 2, 3, 4, 5]), array([ 6,  7,  8,  9, 10])]
Using a for loop to iterate through each element and print:
[1 2 3 4 5] [ 6  7  8  9 10]


NUMPY EXAMPLE PDF

In [22]:
import numpy as np

# Creating array
arr_1d = np.array([1, 2, 3, 4, 5])
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])


# Basic array operations
result = arr_1d + 10
print(f"arr_1d + 10: {result}\n")

result = arr_1d * 2
print(f"arr_1d * 10: {result}\n")

result = arr_1d + arr_1d
print(f"arr_1d + arr_1d: {result}\n")


# Element-wise operations
result = np.sin(arr_1d)
print(f"sin(arr_1d): {result}\n")

result = np.exp(arr_1d)
print(f"exp(arr_1d): {result}\n")


# Matrix Multiplication
result = np.dot(arr_2d, arr_2d)
print(f"Matrix Multiplication (arr_2d * arr_2d): \n{result}\n")

result = arr_1d.T
print(f"Transpose of arr_1d: {result}\n")


# Indexing and Slicing
element = arr_1d[2]
print(f"Element at index 2 of arr_1d: {element}\n")

element = arr_1d[1:4]
print(f"arr_1d[1:4]: {element}\n")

element = arr_2d[:, 1]
print(f"Second column of arr_2d: {element}\n")


# Shape and reshaping
shape = arr_2d.shape
print(f"Shape of arr_2d: {shape}\n")


# Print the original 1D array and the reshaped 2D matrix
arr_1dim = np.array([1, 2, 3, 4, 5, 6])
arr_2dim = arr_1dim.reshape(3, 2)

print(f"Original 1D Array: \n{arr_1dim}")
print(f"Reshaped 2D Matrix: \n{arr_2dim}")

flattened = arr_2d.flatten()
print(f"Flattened arr_2d: {flattened}\n")


# Array Functions
total = np.sum(arr_1d)
print(f"Sum of arr_1d: {total}\n")

average = np.mean(arr_1d)
print(f"Mean of arr_1d: {average}\n")

maximum = np.max(arr_1d)
print(f"Maximum value in arr_1d: {maximum}\n")

greater_than_3 = arr_1d > 3
print(f"Elements greater than 3 in arr_1d: {greater_than_3}\n")

logical_and = np.logical_and(arr_1d > 2, arr_1d < 5)
print(f"Logical AND between arr_1d > 2 and arr_1d < 5: {logical_and}\n")


# Random Number Generation
random_numbers = np.random.rand(3, 3)
print(f"3x3 array of random numbers between 0 and 1: \n{random_numbers}\n")



arr_1d + 10: [11 12 13 14 15]

arr_1d * 10: [ 2  4  6  8 10]

arr_1d + arr_1d: [ 2  4  6  8 10]

sin(arr_1d): [ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]

exp(arr_1d): [  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]

Matrix Multiplication (arr_2d * arr_2d): 
[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]

Transpose of arr_1d: [1 2 3 4 5]

Element at index 2 of arr_1d: 3

arr_1d[1:4]: [2 3 4]

Second column of arr_2d: [2 5 8]

Shape of arr_2d: (3, 3)

Original 1D Array: 
[1 2 3 4 5 6]
Reshaped 2D Matrix: 
[[1 2]
 [3 4]
 [5 6]]
Flattened arr_2d: [1 2 3 4 5 6 7 8 9]

Sum of arr_1d: 15

Mean of arr_1d: 3.0

Maximum value in arr_1d: 5

Elements greater than 3 in arr_1d: [False False False  True  True]

Logical AND between arr_1d > 2 and arr_1d < 5: [False False  True  True False]

3x3 array of random numbers between 0 and 1: 
[[0.54732175 0.45891784 0.95556891]
 [0.80079949 0.62687992 0.06456189]
 [0.62772309 0.63905931 0.5516156 ]]



MORE NUMPY EXAMPLES

In [2]:
import numpy as np
weight = [20, 30, 64, 75, 80]
print(type(weight))
print("\nList : ", weight)

<class 'list'>

List :  [20, 30, 64, 75, 80]


In [24]:
weight_array = np.array(weight)
print(weight_array)
print(weight_array.shape)
print(type(weight_array))

[20 30 64 75 80]
(5,)
<class 'numpy.ndarray'>


In [74]:
import random 
np.random.random(size = 10)

array([0.86849643, 0.90737595, 0.47670262, 0.14349591, 0.69506168,
       0.56075   , 0.50215398, 0.33528246, 0.03701769, 0.05889709])

In [75]:
print(np.random.randint(20,50,5))

[24 36 39 23 47]


In [76]:
np.random.randn(5)

array([ 0.62614208,  0.8394686 ,  1.30350598, -0.84286166, -0.21459377])

In [84]:
even_num = np.arange(start = 10, stop = 20, step = 2)
print(even_num)
print(even_num.shape)
print(even_num.ndim)

[10 12 14 16 18]
(5,)
1


In [78]:
a = np.linspace(start = 0 , stop = 50 , num = 20)
print(a)

[ 0.          2.63157895  5.26315789  7.89473684 10.52631579 13.15789474
 15.78947368 18.42105263 21.05263158 23.68421053 26.31578947 28.94736842
 31.57894737 34.21052632 36.84210526 39.47368421 42.10526316 44.73684211
 47.36842105 50.        ]


In [79]:
np.zeros(shape = 5)

array([0., 0., 0., 0., 0.])

In [80]:
np.ones(shape = 5)

array([1., 1., 1., 1., 1.])

In [3]:
matrix_full = np.full((2,2),fill_value = 3)
print(matrix_full)
print(matrix_full.ndim)
print(matrix_full.shape)

[[3 3]
 [3 3]]
2
(2, 2)


In [4]:
a = np.identity(4)
print(a)


[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [43]:
b_string = np.array(["python", "for", "data", "science"])
b_string

array(['python', 'for', 'data', 'science'], dtype='<U7')

In [3]:
num = np.array([45,89,4,3,55,56,778])

print('no of elements:', num.size)

print('shape of array:', num.shape)

print('dimension of an array:',num.ndim)

print('data type of an array:', num.dtype)

no of elements: 7
shape of array: (7,)
dimension of an array: 1
data type of an array: int32


In [7]:
#numpy array methods:

#reshape

import numpy as np

original_array = np.array([(4, 9), (7, 2),(5,6)])

print('original arrays:\n', original_array)

print(original_array.shape)

original arrays:
 [[4 9]
 [7 2]
 [5 6]]
(3, 2)


In [8]:
reshaped_array = original_array.reshape(2,3)

print('reshaped array: \n', reshaped_array) 
print('shape for reshaped array:', reshaped_array.shape)

reshaped array: 
 [[4 9 7]
 [2 5 6]]
shape for reshaped array: (2, 3)


In [10]:
#arange => note it will convert id to 2d:

num_matrix= np.arange(4)
num_matrix

print('original array ', num_matrix)
print('dimension of an array ', num_matrix.ndim)

original array  [0 1 2 3]
dimension of an array  1


In [11]:
reshaped_matrix = num_matrix.reshape(2,2) 
print('reshaped array ', reshaped_matrix)

reshaped array  [[0 1]
 [2 3]]


In [12]:
# indexing of an array:

age = np.array([23,45,18,26,34,56]) 
print(age)

#1d

#+ve indexing always starts from '0'

#-ve indexing always starts from '-1'

print('last element: ',age[-1]) 
print('fourth element: ', age[3])

[23 45 18 26 34 56]
last element:  56
fourth element:  26


In [13]:
# indexing of 2d arrays:

weight = np.array([(51,45,68), (62,74,55)])

weight

array([[51, 45, 68],
       [62, 74, 55]])

In [14]:
a = weight[0][1]

b= weight[0][2]

print(a)

print(b)

45
68


In [15]:
c= weight[1][1]

d= weight[1][2]

print(c)

print(d)

74
55


In [16]:
#slicing of one dimensional arrays 
age = np.array([23,45,18,26,34,56]) 
print(age) 
print('3rd and 4th element', age[2:4]) 
print('every 2nd element', age[1 :: 2]) 
print('reverse the arrays', age[:: -1]) 
print('elements before 34:', age[:4])

[23 45 18 26 34 56]
3rd and 4th element [18 26]
every 2nd element [45 26 56]
reverse the arrays [56 34 26 18 45 23]
elements before 34: [23 45 18 26]


In [18]:
#slicing of two dimensional arrays

weight = np.array([(51,45,68), (62,74,55)])

print(weight)

#retrive the elements in the 2nd row and 1st two clmns:

print(weight[:]) #all rows

print('2nd row and ist two clmns', weight[1,0:2]) #1-2nd row, 0:2 indexing of 1st t
print(weight[:])
print(weight[:,1:]) #clm wise-row, 1:-clms

[[51 45 68]
 [62 74 55]]
[[51 45 68]
 [62 74 55]]
2nd row and ist two clmns [62 74]
[[51 45 68]
 [62 74 55]]
[[45 68]
 [74 55]]


In [19]:
# Arithmetic opeators:

odd_num= np.array([3,5,7,9])

even_num= np.array ([2,4,6,8])

print('add number array ', odd_num)

print('even number array ', even_num)

sum = odd_num + even_num

print('\nsum ', sum)

print("-"*48)

mynus = odd_num - even_num

print('mynus', mynus)

print('-'*40)

print('updated odd arrays: ',odd_num*2) 
print('updated even arrays: ', even_num*3)

add number array  [3 5 7 9]
even number array  [2 4 6 8]

sum  [ 5  9 13 17]
------------------------------------------------
mynus [1 1 1 1]
----------------------------------------
updated odd arrays:  [ 6 10 14 18]
updated even arrays:  [ 6 12 18 24]


In [20]:
#comparison operators in an array:

#it can be used to validate specific condition:

#it follows with condition on each elements

import numpy as np

age= np.array([14,56,43,98,34,77,22])

print(age>40) #it will give booolean output 
print('AGe greater than 40:', age [age>40])

[False  True  True  True False  True False]
AGe greater than 40: [56 43 98 77]


In [21]:
# arithmetic operations on 2d array:

num_matrix_1 = np.array([[1,0,2], [4,-2,3]])

num_matrix_2 = np.array([[4,8,1], [2,3,8]])

print(num_matrix_1)

print(num_matrix_2)

product = num_matrix_1*num_matrix_2

print('element wise multiplication:\n', product)

[[ 1  0  2]
 [ 4 -2  3]]
[[4 8 1]
 [2 3 8]]
element wise multiplication:
 [[ 4  0  2]
 [ 8 -6 24]]


In [22]:
#different shapes

num_1= np.array([[1,0,2], [4,-2,3]])

num_2= np.array([[4,0], [2,3], [1,4]])

print(num_1)

print(num_2)

#dot function for multiplication of 2*3 and 3*2

mul = num_1.dot(num_2)

print(mul)

[[ 1  0  2]
 [ 4 -2  3]]
[[4 0]
 [2 3]
 [1 4]]
[[ 6  8]
 [15  6]]


In [23]:
# simple arithmetic functions on array
age = np.array([14, 56, 43, 98, 34, 77, 22])
#USING KEYWORDS MIN, MAX, SUM, MEAN, VAR, STD, SQUARE, POWER

print('Minimum: ',age.min())

print('Maximum: ',age.max())

print('Sum: ',age.sum())

print('Mean: ', round(age.mean(),3))

print('variance: ',age.var())

print('standard deviation', age.std())

print('Square:', np.square(age))

print('cube:', np. power (age, 3))

Minimum:  14
Maximum:  98
Sum:  344
Mean:  49.143
variance:  778.4081632653061
standard deviation 27.89996708358822
Square: [ 196 3136 1849 9604 1156 5929  484]
cube: [  2744 175616  79507 941192  39304 456533  10648]


In [24]:
#TRANSPOSE OF AN ARRAY:

num= np.array([[1,2,3], [4,5,6]])

print('Origianl array: \n', num)

print('Tranposed array: \n', np. transpose(num))

Origianl array: 
 [[1 2 3]
 [4 5 6]]
Tranposed array: 
 [[1 4]
 [2 5]
 [3 6]]


In [28]:
#Conacatenation of id array:

order_1 = np.array([1,4,5,7]) 
order_2 = np.array([5,6,7])
order_3 = np.array([2,7,8,9])

np.concatenate([order_1, order_2, order_3])

array([1, 4, 5, 7, 5, 6, 7, 2, 7, 8, 9])

In [30]:
#we can concatenate 2d array either along the rows (axis-8) (BY DEFAULT)

#we can concatenate 20 array either along the cims(axis-1)

odd_array = np.array([[1,3],[5,7]])
even_array = np.array([[2,4],[6,8]])

print('ODD ARRAYS: ',odd_array)
print('EVEN ARRAYS: ', even_array)
print('ROW WISE CONCATENATION OF 2D ARRAY ', np.concatenate([odd_array, even_array]))

print('CLMN WISE CONCATENATION OF 2D ARRAY ', np.concatenate([odd_array, even_array],axis =1))

ODD ARRAYS:  [[1 3]
 [5 7]]
EVEN ARRAYS:  [[2 4]
 [6 8]]
ROW WISE CONCATENATION OF 2D ARRAY  [[1 3]
 [5 7]
 [2 4]
 [6 8]]
CLMN WISE CONCATENATION OF 2D ARRAY  [[1 3 2 4]
 [5 7 6 8]]


In [31]:
# Stacking of an arrays are used to join two or more arrays 
# with the same shape along with the specified axis
# we can create higher-dimensional arrays by stackking two or more arrays

import numpy as np

odd_array = np.array([[1,3], [5,7]])

even_array = np.array([[2,4], [6,8]])

print("Odd arrays:\n", odd_array)
print('Even arrays:\n', even_array)
print('stacked arrays: \n', np.stack([odd_array, even_array])) 
print('dimension: ', np.ndim(np.stack([odd_array, even_array])))

Odd arrays:
 [[1 3]
 [5 7]]
Even arrays:
 [[2 4]
 [6 8]]
stacked arrays: 
 [[[1 3]
  [5 7]]

 [[2 4]
  [6 8]]]
dimension:  3


In [32]:
odd_array = np.array([[1,3], [5,7]])

even_array = np.array([[2,4], [6,8]])

print(np.hstack([odd_array, even_array]))
print()
print(np.vstack([odd_array, even_array]))

[[1 3 2 4]
 [5 7 6 8]]

[[1 3]
 [5 7]
 [2 4]
 [6 8]]


In [33]:
#Column stacking for 10 and 2D arrays:
#hstack columnstack
#1D

odd_array = np.array([1,3])
even_array = np.array([2,4])
np.column_stack([odd_array, even_array])

array([[1, 2],
       [3, 4]])

In [34]:
#20 

odd_array = np.array([[1,3], [5,7]])
even_array = np.array([[2,4], [6,8]]) 
np.column_stack([odd_array, even_array])

array([[1, 3, 2, 4],
       [5, 7, 6, 8]])

In [35]:
#-block()
#it is used to assemble arrays from a nested list into blocks

m1 = np.zeros((2,2)) 
m2 = np.ones((2,2))
m3 = np.zeros((2,2))
m4 = np.ones((2,2))

np.block([[m1,m2], [m3,m4]])

array([[0., 0., 1., 1.],
       [0., 0., 1., 1.],
       [0., 0., 1., 1.],
       [0., 0., 1., 1.]])

In [37]:
#Spliting of an array
#Consider on 10 array
#Split

num_array = np.arange(9)
print('spliting of an array at specific indices:\n',np.split(num_array, [1,3]))

spliting of an array at specific indices:
 [array([0]), array([1, 2]), array([3, 4, 5, 6, 7, 8])]


In [38]:
num_array = np.arange(9)
print('2 sub- arrays:', np.array_split(num_array, 2))

2 sub- arrays: [array([0, 1, 2, 3, 4]), array([5, 6, 7, 8])]


In [39]:
#Splitting an array using hsplit()
#create an 2d array

num_array = np.array([[1,3,5,7], [2,4,6,8]])

#split the array into two sub arrays

np.hsplit(num_array,2)

[array([[1, 3],
        [2, 4]]),
 array([[5, 7],
        [6, 8]])]

In [40]:
# Splitting an array using vsplit()
#create 2D array

num_array = np.array([[1,3,5,7], [2,4,6,8]])

#split the array into 2 sub arrays 
np.vsplit(num_array, 2)

[array([[1, 3, 5, 7]]), array([[2, 4, 6, 8]])]

In [41]:
# Splitting an array depth-wise using dsplit()

num_array = np.arange(16).reshape(2,4,2)

#Split the array into 2 sub-arrays

print('splitted array', np.dsplit(num_array,2))

splitted array [array([[[ 0],
        [ 2],
        [ 4],
        [ 6]],

       [[ 8],
        [10],
        [12],
        [14]]]), array([[[ 1],
        [ 3],
        [ 5],
        [ 7]],

       [[ 9],
        [11],
        [13],
        [15]]])]


In [42]:
#create an 2d array
num_array = np.array([[1,3,5,7], [2,4,6,8]])

print('Original array:\n', num_array)
print('dimentionality of the array:',np.ndim(num_array))

#flatten the array into 10
print("flattened array: \n", np.ndarray.flatten (num_array))
print('dimentionality of the array: ', np.ndim(np.ndarray.flatten (num_array)))

Original array:
 [[1 3 5 7]
 [2 4 6 8]]
dimentionality of the array: 2
flattened array: 
 [1 3 5 7 2 4 6 8]
dimentionality of the array:  1


1D[Create ndarray, mean, dot(2 x 3) (3 x 2), reshape, flatten, dtype, reverse ndarray, sort(ascending, descending)], 1D: swap values with another array, random.rand(5,5) find min, max and mean

In [105]:
import numpy as np
import random

# Create
arr_1d = np.array([1, 2, 3, 4, 5])

# Mean
average = np.mean(arr_1d)
print(f"Mean: {average}\n")

array1 = np.random.randint(10, size=(3, 3))
array2 = np.random.randint(10, size=(3, 3))

# Calculate dot product
result = np.dot(array1, array2)

# Display arrays and dot product
print(f"Array 1:\n{array1}")
print(f"Array 2:\n{array2}")
print(f"Product:\n{result}\n")

# Reshape
reshape = result.reshape(1,9)
print(f"Reshape of the product above:\n{reshape}\n")

# Flatten
flatten = result.flatten()
print(f"Flatten of the product:\n{flatten}\n")

# Dtype
dtype = result.dtype
print(f"Type of the product: {dtype}\n")

# Reverse ndarray
reverse = reshape[::-1 , ::-1]
reversef = flatten[::-1]
print(f"Reverse of 2D: {reverse}")
print(f"Reverse of 1D: {reversef}\n")

# Ascending and descending

# Min and max of Random array of size (5,5)
rand_array = np.random.randint(10, size=(5,5))
print(f"Random (5,5) array:\n{rand_array}")
print(f"Min of Reshape: {rand_array.min()}")
print(f"Max of Reshape: {rand_array.max()}\n")

# Swap  
a = np.array([1, 2, 3])
b = np.array([3, 4, 5])

print("Original")
print(f"a = {a}")
print(f"b = {b}")

a = a + b
b = a - b
a = a - b

print("After swap: ")
print(f"a = {a}")
print(f"b = {b}\n")



Mean: 3.0

Array 1:
[[7 6 7]
 [4 8 1]
 [1 6 3]]
Array 2:
[[9 0 1]
 [4 1 5]
 [6 4 1]]
Product:
[[129  34  44]
 [ 74  12  45]
 [ 51  18  34]]

Reshape of the product above:
[[129  34  44  74  12  45  51  18  34]]

Flatten of the product:
[129  34  44  74  12  45  51  18  34]

Type of the product: int32

Reverse of 2D: [[ 34  18  51  45  12  74  44  34 129]]
Reverse of 1D: [ 34  18  51  45  12  74  44  34 129]

Random (5,5) array:
[[9 3 4 0 4]
 [5 9 7 1 6]
 [7 7 0 4 3]
 [4 4 5 8 3]
 [0 2 8 7 9]]
Min of Reshape: 0
Max of Reshape: 9

Original
a = [1 2 3]
b = [3 4 5]
After swap: 
a = [3 4 5]
b = [1 2 3]

